spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true	  
logging:
  level:
    root: INFO

# Customize other properties here
